name: Build GraphScope Wheels on Linux

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    paths-ignore:
      - 'CONTRIBUTORS'
      - 'LICENSE'
      - 'NOTICE.txt'
      - '**.md'
      - '**.rst'
      - 'docs/**'
      - 'demo/**'
      - 'scripts/**'
      - 'tutorials/**'
  pull_request:
    paths-ignore:
      - 'CONTRIBUTORS'
      - 'LICENSE'
      - 'NOTICE.txt'
      - '**.md'
      - '**.rst'
      - 'docs/**'
      - 'demo/**'
      - 'scripts/**'
      - 'tutorials/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/gss.yml'
      - '.github/workflows/gaia.yml'
      - '.github/workflows/gae.yml'
      - '.github/workflows/nightly.yml'
      - '.github/workflows/networkx-forward-algo-nightly.yml'
      - '.github/workflows/build-graphscope-wheels-linux.yml'
      - '.github/workflows/build-graphscope-wheels-maos.yml'


jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup tmate session
      if: false
      uses: mxschmitt/action-tmate@v2

    - name: Build Wheel Package
      run: |
        # Due to an observation of changing hostname in github runners,
        # append 127.0.0.1 to etc/hosts to avoid DNS lookup.
        r=`cat /etc/hosts | grep $(hostname) || true`
        if [ -z "${r}" ];then export hn=$(hostname); sudo -E bash -c 'echo "127.0.0.1 ${hn}" >> /etc/hosts'; fi
        cat /etc/hosts

        cd ${GITHUB_WORKSPACE}/k8s
        # build graphscope wheels
        sudo -E make graphscope-py3-package

        # build client wheels
        sudo -E make graphscope-client-py3-package

        # package
        cd ${GITHUB_WORKSPACE}
        tar -zcf client.tar.gz python/dist/wheelhouse/*.whl
        tar -zcf graphscope.tar.gz coordinator/dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheel-${{ github.sha }}
        path: |
          client.tar.gz
          graphscope.tar.gz
        retention-days: 5
